version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/queue-system
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "17930:6379"
    environment:
      - REDIS_PASSWORD=pEKdkfdEo3826lyBpAILcLTgAzYbNAqw
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
